### ISSUE TITLE
Error shared library under alpine server

### ISSUE THREAD

**Issue by gezabenko** [spritsail/plex-media-server#11]
Hi!

I tried to start the new versions (1.15) under Alpine Linux, but I always get the following error message:
```/usr/lib/plexmediaserver/Plex Media Server: error while loading shared libraries: libgnsdk_dsp.so.3.10.1: cannot enable executable stack as shared object requires: Permission denied```

 The older ones (1.14 and before) work without error. Is it possible to work with the new versions? Thanks in advance!

**Comment by frebib** [comment]
`cannot enable executable stack as shared object requires: Permission denied` is a strange error. Are you running a custom kernel like SELinux or grsec or something? It could be a 1.15 thing although it seems to be working ok for me on Debian. Are you trying the stable or the pass branch?

**Comment by frebib** [comment]
https://forums.plex.tv/t/pms-0-9-12-on-selinux/101652/4

Apparently this is an old issue. I don't know if it is the fault of Plex or ours but I can probably fix it in our container at least, as suggested in the forum post above:
```
execstack -c /usr/lib/plexmediaserver/libgnsdk_dsp.so.3.10.1
```

Can you try running that command on the library and testing to see if it works? You'll probably have to do it in the Dockerfile and rebuilid because I'm certain that `execstack` won't be in the built image

**Comment by frebib** [comment]
I'll do you one better. Try the tag `:execstack-1.15` and let me know if that fixes it, and I'll merge it to master :)

**Comment by gezabenko** [comment]
Hi! 

I tried to find some workaround on it, but I couldn't find it :( . I've tried it now and it works perfectly with the :execstack-1.15 tag :). 

Thank you very much for your quick response and have a nice day ;).

**Comment by gezabenko** [comment]
Sorry, though I closed the ticket, but the merge would still be needed in the long run ;) . Thx
