### ISSUE TITLE
What exactly was removed?

### ISSUE THREAD

**Issue by wisewtf** [spritsail/plex-media-server#39]
Hello,

I feel like the README is lacking information. All the 'useless crap' removed sounds good, as I can probably ASSUME what it is. But wouldn't it be better if you specify exactly what it is that was removed?

As you also say 'fully functional'. 

Thank you for your work and time.

**Comment by frebib** [comment]
Good question. I'll have a go at summarising here (it's been a while since we did this so I'm working mostly from memory)
- Compared with other popular images such as lsio and the first-party plex image, ours is based `FROM scratch`, meaning the only things in the image are Plex Media Server itself, libc+busybox and a few libraries. The other images ship an entire OS which is clearly pointless, when Plex works just fine without any of that.
- Many bundled libraries that Plex ships are redundant because the host OS also ships them. In many cases, we've removed the bundled libraries and rebuilt them from source, including only the features that Plex needs and nothing else, to reduce the image size.
- There's also a `nofonts` branch (that hasn't had updates in a while) which also removes about 1/4 of the image size in just Noto fonts, that from what I can tell are only used for baking in subtitles- if you don't use subtitles then that is some additional saving.

The premise here was to create an image that is based on "start with nothing and only include what you need" instead of the popular principle of "start with something fully-featured and just add stuff until it works"

```
REPOSITORY                    TAG           IMAGE ID       CREATED         SIZE
linuxserver/plex              latest        adb476b21424   10 days ago     383MB
plexinc/pms-docker            latest        799dd237b657   10 days ago     373MB
spritsail/plex-media-server   latest        6d1e02fc3cac   10 days ago     241MB
```
This approach allowed us to ship literally just Plex and nothing else in 62% the size of the lsio image, and 64% the size of the official image
