### ISSUE TITLE
Add timezone variable/bind mount option.

### ISSUE THREAD

**Issue by purrsevere** [spritsail/plex-media-server#7]
I don't see any way to set the timezone. It defaults to UTC and would like to change that.

Typical approaches for setting timezone in docker containers would be to either set an environment variable or bind mount /etc/localtime or /etc/timezone.

Neither of these options work, unless I'm doing something wrong.

**Comment by frebib** [comment]
I think I'm using the bind mount method successfully. What is the mount string you're using?
I've looked into the whole `TZ` variable thing in the past but I dismissed it because a) it's a thing provided by supervisor (the container init) and b) it requires several megabytes of extra TZ data that won't be used by 99% of users.

 It's something I'd definitely like to tackle for all of our containers but I can't seem to come up with a decent solution that doesn't increase the size of the container/download extra stuff at runtime/cause too much of a headache for the user. I'm definitely leaning towards downloading the single tzinfo data file for the specified container at runtime although it's not an ideal solution.

Have you got any better ideas?

**Comment by frebib** [comment]
Bump, @PurrSevere did you try using the bind-mount again?

As for the TZ variable, hopefully we'll find time to work out how to do that. I'm now working full time so my time for these projects is limited. Your input is welcomed if you have any :)

**Comment by purrsevere** [comment]
Hey there! So it turns out I was mounting the wrong localtime file. Sorry about that. It's working properly now.
